services:
  app:
    build: .
    container_name: sender_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22iamgewog22
      POSTGRES_DB: server
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data